on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: pkgbuild-win-11-arm-test

permissions: read-all

jobs:
  pkgbuild-win-11-arm-test:
    runs-on: windows-11-arm

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install R and RTools for Windows on ARM, install pkgbuild and test run pkgbuild check_build_tools()
        run: |
          # Install R aarch64 4.5.0
          $url = "https://www.r-project.org/nosvn/winutf8/aarch64/R-4-signed/R-4.5.0-aarch64.exe"
          Invoke-WebRequest -Uri "$url" -OutFile R-4.5.0-aarch64.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath R-4.5.0-aarch64.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait

          # Install Rtools45
          $url = "https://cran.r-project.org/bin/windows/Rtools/rtools45/files/rtools45-aarch64-6536-6492.exe"
          Invoke-WebRequest -Uri "$url" -OutFile rtools45-aarch64-6536-6492.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath rtools45-aarch64-6536-6492.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          
          # Add R and Rtool45 binaries to PATH
          $ENV:PATH = "C:\Program Files\R-aarch64\R-4.5.0\bin;C:\rtools45-aarch64\usr\bin;$ENV:PATH"
          
          # Install pandoc
          choco install pandoc

          # Install pkgbuild and run test
          $rscript = "Rscript"
          $args = "-e", "print(R.version); install.packages('pkgbuild', repos = 'https://cloud.r-project.org/'); print('check_build_tools()'); pkgbuild::check_build_tools(debug = TRUE); print('has_rtools()'); pkgbuild::has_rtools(debug = TRUE); print('rtools_path()'); pkgbuild::rtools_path()"
          & $rscript $args
